behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 8192
      learning_rate: 0.0005
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 96
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 20000